onboarding = false

[theme]
name = "catppuccin"
auto_switch = false

[keys]
focus_pane_left = ["prefix+h", "alt+h"]
focus_pane_down = ["prefix+j", "alt+j"]
focus_pane_up = ["prefix+k", "alt+k"]
focus_pane_right = ["prefix+l", "alt+l"]
previous_tab = ["prefix+p", "alt+left"]
next_tab = ["prefix+n", "alt+right"]
new_tab = ["prefix+c", "alt+n"]
previous_workspace = "alt+up"
next_workspace = "alt+down"
