# https://wiki.hypr.land/hyprland-wiki/pages/Configuring/Window-Rules/

# Ignore maximize requests from all apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus true

# Hyprland-run windowrule
windowrule = match:class hyprland-run, move 20 monitor_h-120, float yes

# Floating windows
windowrule = match:class ^(obsidian)$, float on, size 1200 1500
windowrule = match:title ^(btop)$, size 1300 850, move 40 70, float on
windowrule = match:class ^(Cssh|galculator|zoom)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:title ^(Open|Save) (File|Folder|As|file|folder|as).*$, float on, size 1400 1000
windowrule = match:title .*(wants to open)$, float on
windowrule = match:title .* is sharing your screen\.$, float on
windowrule = match:class ^(launcher)$, border_size 0,opacity 0.8
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on, size 1600 1000, move 40 70

# Inhibit idle
windowrule = match:class ^(Firefox)$, match:title = ^(Meet - .*-.*-.*)$, idle_inhibit focus
windowrule = match:class ^(Firefox)$, match:title = ^(Meet - .*-.*-.*)$, idle_inhibit focus

# Zoom
windowrule = match:class ^(zoom)$,match:title = ^(Choose ONE of the audio conference options|zoom)$, float on
windowrule = match:class ^(zoom)$,match:title = ^(Zoom Meeting|Zoom - Free Account)$, tile on
windowrule = match:class ^(zoom)$, idle_inhibit fullscreen
